spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spotty?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username:
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          spotify:
            provider: spotify-provider
            client-id:
            client-secret:
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/oauth2/callback/spotty"
            scope: "user-top-read,user-read-email,user-read-private"
        provider:
          spotify-provider:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: "display_name"
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
